# Cloudflare Workers config
# El usuario debe reemplazar el ID del KV namespace con el real creado en Cloudflare Dashboard

name = "auto-helpdesk"
compatibility_date = "2024-09-23"
main = "worker.ts"

[assets]
directory = "dist"

[[kv_namespaces]]
binding = "KV_ZOHO"
id = "dd58f8f1742d4943b8faaeb3912700ce"
